# Generated by Django 4.2.9 on 2024-01-12 11:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0002_alter_player_first_name_alter_player_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='display_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
